# Generated by Django 2.0.1 on 2018-03-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashAgreement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('issuer', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CashIOU',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('issuer', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChangeIssuerDelegation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('delegate', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProposalToChangeIssuer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cashToSwap', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('targetParty', models.CharField(max_length=100)),
                ('triggerParty', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SwapProposal',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cashToSwap', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('targetParty', models.CharField(max_length=100)),
                ('triggerParty', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
